name: Pull Request Checks
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  commitlint:
    name: Commit Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Lint Code
        run: npm run lint
      - name: Lint Title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: npx --no-install commitlint <<< "$TITLE"
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      cf_zone_id: ${{ secrets.CF_ZONE_ID }}
      cf_api_token: ${{ secrets.CF_API_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - name: Bypass Cloudflare for GitHub Action
        if: ${{ env.cf_api_token != ''&&  env.cf_zone_id != '' }}
        uses: xiaotianxt/bypass-cloudflare-for-github-action@v1.1.1
        with:
          cf_zone_id: ${{ env.cf_zone_id }}
          cf_api_token: ${{ env.cf_api_token }}
      - uses: leafo/gh-actions-lua@v11.0.0
      - uses: actions/cache@v4
        with:
          path: data/json
          key: ${{ runner.os }}-${{ github.run_id }}${{ github.run_number }}
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - run: npm ci
      - run: npm i -D warframe-patchlogs@^2
      - run: npm i --no-save warframe-worldstate-data@^3
      - run: npm run build -- --force
        env:
          PROXY_TYPE: ${{ secrets.PROXY_TYPE }}
          PROXY_SOCKS5_USER: ${{ secrets.PROXY_SOCKS5_USER }}
          PROXY_SOCKS5_PASS: ${{ secrets.PROXY_SOCKS5_PASS }}
          PROXY_SOCKS5_HOST: ${{ secrets.PROXY_SOCKS5_HOST }}
          PROXY_SOCKS5_PORT: ${{ secrets.PROXY_SOCKS5_PORT }}
          PROXY_HTTPS_STRING: ${{ secrets.PROXY_HTTPS_STRING }}
  types:
    name: Type Checks
    runs-on: ubuntu-latest
    needs: [build, lint]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: data/json
          key: ${{ runner.os }}-${{ github.run_id }}${{ github.run_number }}
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - run: npm ci
      - run: npm run typings
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build, lint]
    strategy:
      matrix:
        node-version:
          - 'lts/*'
          - 20
          - 22
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: data/json
          key: ${{ runner.os }}-${{ github.run_id }}${{ github.run_number }}
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - run: npm i -D warframe-patchlogs@^2
      - run: npm i --no-save warframe-worldstate-data@^3
      - name: Test
        env:
          NODE_OPTIONS: '--max_old_space_size=2048'
        run: npm test
      - name: Regression
        env:
          NODE_OPTIONS: --experimental-fetch
        run: npm run regression
